---
title: "Titulo pdf"
author: "Alisson Rosa"
header-includes:
   - \usepackage[brazil]{babel}
geometry: margin=2cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
---



```{r setup,,include=F,}
#https://www.animefillerguide.com/2019/06/naruto-shippuden-filler-list.html
#https://en.wikipedia.org/wiki/List_of_Naruto:_Shippuden_episodes#Season_6_(2009–10)
library('tidyverse')
library("tidymodels")
library('kableExtra')
options(digits=2)
theme_set(theme_minimal())
knitr::opts_chunk$set(echo=FALSE,message=F,warning=F,fig.pos = 'H',fig.align = 'center',fig.width=7.8, fig.height=4.85)
scale_fill_discrete = \(...) scale_fill_brewer(... , palette="Set2")

```
##Limpeza dos dados
```{r dc}
df <- "https://www.animefillerlist.com/shows/naruto-shippuden" %>%
  rvest::read_html() %>%
  rvest::html_node(xpath = '//*[@id="node-18"]/div[3]/table') %>%
  rvest::html_table()

Saga <- c(
  rep("Kazekage Rescue (1) ", 32), 
  rep("Long-Awaited Reunion (2)", 21),
  rep("Twelve Guardian Ninja (3)", 18),
  rep("Immortal Devastators (4)", 17),
  rep("The Three-Tailed Demon Turtle (5)",24), 
  rep("Prophecy and Vengeance (6)",31),
  rep("The Six-Tailed Demon Slug (7)",8),
  rep("Two Saviors (8)",24),
  rep("The Locus Of Konoha (9)",21),
  rep("The Gathering of the Five Kage (10)", 25),
  rep("Paradise On The Ship (11)", 21),
  rep("Nine-Tailed Fox Taming And Karmic Encounters (12)", 33),
  rep("The Seven Shinobi Swordsmen (13)", 20),
  rep(" The Fourth Great Ninja War - Assailants From Afar (14)", 25),
  rep("The Fourth Great Ninja War - Sasuke And Itachi (15)",28),
  rep("Kakashi: Shadow Of The Anbu Black Ops (16)",13),
  rep("The Fourth Great Ninja War - The Return Of Squad Seven (17)",11),
  rep("The Fourth Great Ninja War - Obito Uchiha Against The Shinobi Forces (18)",21),
  rep("Naruto'S Back ~The Tracks Of His Friends (19)",20),
  rep("Infinite Tsukuyomi: The Invocation (20)",66),
  rep("Series (21)",21)
  
)



page <- function(st) {
  httr::GET(
    paste0(paste0(
      "https://www.ratingraph.com/show-episodes-list/27282/?draw=1&columns%5B0%5D%5Bdata%5D=trend&",
      "columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=season&",
      "columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=false&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=episode&",
      "columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=false&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=name&",
      "columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=false&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=start&",
      "columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=false&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=total_votes&",
      "columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=false&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=average_rating&",
      "columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=false&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&",
      "order%5B0%5D%5Bdir%5D=asc&order%5B1%5D%5Bcolumn%5D=2&order%5B1%5D%5Bdir%5D=asc&start=", st, "&length=250&search%5Bvalue%5D=&search%5Bregex%5D=false&_="
    ), Sys.time() %>% as.numeric() %>% paste0("000"))
  )
}

```

```{r}
avg <- function(start) {
  page(start) %>%
    httr::content(as = "parsed") %>%
    .$data %>%
    sapply(`[[`, "average_rating") %>%
    as.numeric()
}
tot <- function(start) {
  page(start) %>%
    httr::content(as = "parsed") %>%
    .$data %>%
    sapply(`[[`, "total_votes") %>%
    gsub(pattern = ",", replacement = "", x = ., fixed = TRUE) %>%
    as.numeric()
}
avg250 <- avg(0)
avg500 <- avg(250)
avg_rating <- c(avg(0), avg(250))
total_votes <- c(tot(0), tot(250))
```


```{r}
df=df %>%
  rename(numero_episodio = `#`, Titulo = Title, Tipo = Type) %>%
  bind_cols(rate = avg_rating, votes = total_votes,Saga=Saga) %>% 
separate(Airdate, c("Lançamento")) %>%
  mutate(Lançamento = as.numeric(Lançamento),Tipo=as.factor(Tipo))
```



##Análise Exploratória

```{r ead}

```


##Modelagem

```{r mod}

```

##Avaliação da modelagem

```{r}

```

